theme: jekyll-theme-slate
title: Black Friday Sale
description: This notebook contain the sale prediction of the company called ABC company. The company wants to create the machine learning model to predict and understand the customer purchase behaviour.
